#!/usr/bin/env bash
# Auto-generated by fetch_conserved_genes.py
# Runs salmon index on conserved housekeeping genes, then quant on all samples.

set -euo pipefail

FASTA="combined/all_kingdoms_combined.fasta"
INDEX_DIR="./salmon_index_housekeeping"
THREADS=8

# ── 1. Build the salmon index ──────────────────────────────────────────────
echo '>>> Building salmon index …'
salmon index \
    -t "${FASTA}" \
    -i "${INDEX_DIR}" \
    --threads "${THREADS}" \
    --keepDuplicates

echo 'Index built at '"${INDEX_DIR}"

# ── 2. Quantify each sample ────────────────────────────────────────────────
# Edit SAMPLES array: each entry is a sample name; reads assumed at
#   ./reads/<sample>_R1.fastq.gz  ./reads/<sample>_R2.fastq.gz
SAMPLES=(sample1 sample2 sample3)
READS_DIR="./reads"
QUANT_DIR="./salmon_quant"

mkdir -p "${QUANT_DIR}"

for SAMPLE in "${SAMPLES[@]}"; do
    echo ">>> Quantifying ${SAMPLE} …"
    salmon quant \
        -i  "${INDEX_DIR}" \
        -l  A \
        -1  "${READS_DIR}/${SAMPLE}_R1.fastq.gz" \
        -2  "${READS_DIR}/${SAMPLE}_R2.fastq.gz" \
        -p  "${THREADS}" \
        --validateMappings \
        --gcBias \
        --seqBias \
        -o  "${QUANT_DIR}/${SAMPLE}"
done

echo '>>> All quantifications complete.'
echo 'Results are in '"${QUANT_DIR}"
