[workspace]
authors = ["gabrielvpina <gvpina.rodrigues@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "viralquest"
platforms = ["linux-64"]
version = "3.0.0"

[tasks]
start             = "python main.py"
viralquest        = "python main.py"
viralquest-setup  = "python -c 'from viralquest.setup_env import setup; setup()'"
viralquest-download = "python -c 'from viralquest.setup_env import download; download()'"
install-editable  = "pip install -e ."

[dependencies]
python = "3.12.*"
pandas = ">=3.0.2,<4"
numpy = ">=2.4.3,<3"
biopython = ">=1.87,<2"
tqdm = ">=4.67.3,<5"
loguru = ">=0.7.3,<0.8"
httpx = ">=0.28.1,<0.29"
requests = ">=2.33.1,<3"
pooch = ">=1.9.0,<2"
orfipy = ">=0.0.4,<0.0.5"
pytest = ">=9.0.3,<10"
diamond = ">=2.1.24,<3"
blast   = ">=2.16,<3"
pyhmmer = ">=0.12.0,<0.13"
cap3    = ">=10.2011,<11"
salmon  = ">=1.11.4,<2"
rich = ">=15.0.0,<16"
setproctitle = ">=1.3.7,<2"

[pypi-dependencies]
bio = ">=1.8.1, <2"
biothings-client = ">=0.5.0, <0.6"
gprofiler-official = ">=1.0.0, <2"
mygene = ">=3.2.2, <4"
loguru = "*"
orfipy = ">=0.0.4, <0.0.5"
gdown = ">=5.0"
ollama = ">=0.4.7"
openai = ">=1.0.0"
anthropic = ">=0.40.0"
google-genai = ">=1.0.0"

